spring:
  profiles:
    active: local
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: jdbc:log4jdbc:mariadb://localhost:13306/aurum_dev
#    hikari:
#      username: dev_user
#      password: dev_user

