server:
  port: 8080



spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate  #create-drop, update, validate, none

# jwt.secret.key
jwt:
  secret:
    salt: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M